export const styles = {
  container: {
    position: 'relative',
    width: '100%',
    height: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
  },
  canvas: {
    border: '2px solid #333',
    borderRadius: '4px',
  },
  hiddenCanvas: {
    display: 'none',
  },
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100vh',
    backgroundColor: '#1a1a1a',
    color: 'white',
    fontFamily: 'Arial, sans-serif',
  },
  statsBox: {
    position: 'relative',
    display: 'inline-block',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    color: 'white',
    padding: '10px',
    borderRadius: '5px',
    fontFamily: 'monospace',
    fontSize: '14px',
    minWidth: '150px',
  },
  trackSelect: {
    padding: '9.5px 16px',
    backgroundColor: '#666',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontFamily: 'monospace',
    fontSize: '14px',
    whiteSpace: 'nowrap',
  },
  boundingBoxButton: {
    padding: '8px 16px',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontFamily: 'monospace',
    fontSize: '14px',
    whiteSpace: 'nowrap',
  },
  backButton: {
    padding: '8px 16px',
    backgroundColor: '#666',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontFamily: 'monospace',
    fontSize: '14px',
    whiteSpace: 'nowrap',
  },
  buttonContainer: {
    position: 'absolute',
    top: '10px',
    right: '10px',
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
  },
  onTrack: {
    color: '#44ff44',
  },
  offTrack: {
    color: '#ff4444',
  },
  showBoundingBox: {
    backgroundColor: '#44ff44',
  },
  hideBoundingBox: {
    backgroundColor: '#ff4444',
  },
} as const; 